Import Library dan sejenisnya

In [1]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from collections import OrderedDict
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC
plt.ion()

memanggil dataset

In [2]:
dataset = "https://raw.githubusercontent.com/kb22/Heart-Disease-Prediction/master/dataset.csv"
data = pd.read_csv(dataset)
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

Memisahkan Data sesuai column yang diinginkan

In [3]:
data.head()
data1 = data.drop(columns=['sex', 'target'])

In [4]:
data2 = data[["sex"]]

In [5]:
data2.head(25)

sex
0     1
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     1
9     1
10    1
11    0
12    1
13    1
14    0
15    0
16    0
17    0
18    1
19    0
20    1
21    1
22    1
23    1
24    1

In [6]:
datasex = pd.get_dummies(data2)
datasex

sex
0      1
1      1
2      0
3      1
4      0
..   ...
298    0
299    1
300    1
301    1
302    0

[303 rows x 1 columns]

In [7]:
data3 = data[["target"]]

In [8]:
data3.head(25)

target
0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1

In [9]:
datatarget = pd.get_dummies(data3)
datatarget

target
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

In [10]:
datanumeric = pd.concat([datasex, datatarget], axis=1)

untuk menyatukan data yang sudah di split

In [11]:
Hasil = pd.concat([data1, datanumeric], axis=1)
Hasil

age  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0     63   3       145   233    1        0      150      0      2.3      0   
1     37   2       130   250    0        1      187      0      3.5      0   
2     41   1       130   204    0        0      172      0      1.4      2   
3     56   1       120   236    0        1      178      0      0.8      2   
4     57   0       120   354    0        1      163      1      0.6      2   
..   ...  ..       ...   ...  ...      ...      ...    ...      ...    ...   
298   57   0       140   241    0        1      123      1      0.2      1   
299   45   3       110   264    0        1      132      0      1.2      1   
300   68   0       144   193    1        1      141      0      3.4      1   
301   57   0       130   131    0        1      115      1      1.2      1   
302   57   1       130   236    0        0      174      0      0.0      1   

     ca  thal  sex  target  
0     0     1    1       1  
1     0     2    1       1  
2     0     2    0       1  
3     0     2    1       1  
4     0     2    0       1  
..   ..   ...  ...     ...  
298   0     3    0       0  
299   0     3    1       0  
300   2     3    1       0  
301   1     3    1       0  
302   1     2    0       0  

[303 rows x 14 columns]

proses normalisasi data

In [12]:
dataNormalisasi = ['age',	'trestbps',	'chol',	'thalach', 'oldpeak', 'slope', 'ca', 'thal']
FrameNormalisasi = Hasil[dataNormalisasi]
FrameNormalisasi

age  trestbps  chol  thalach  oldpeak  slope  ca  thal
0     63       145   233      150      2.3      0   0     1
1     37       130   250      187      3.5      0   0     2
2     41       130   204      172      1.4      2   0     2
3     56       120   236      178      0.8      2   0     2
4     57       120   354      163      0.6      2   0     2
..   ...       ...   ...      ...      ...    ...  ..   ...
298   57       140   241      123      0.2      1   0     3
299   45       110   264      132      1.2      1   0     3
300   68       144   193      141      3.4      1   2     3
301   57       130   131      115      1.2      1   1     3
302   57       130   236      174      0.0      1   1     2

[303 rows x 8 columns]

In [13]:
scaler = MinMaxScaler()

In [14]:
scaler.fit(FrameNormalisasi)

MinMaxScaler()

In [15]:
hasilNormalisasi = scaler.transform(FrameNormalisasi)

In [16]:
hasilNormalisasi = pd.DataFrame(hasilNormalisasi,columns = dataNormalisasi)
hasilNormalisasi

age  trestbps      chol   thalach   oldpeak  slope    ca      thal
0    0.708333  0.481132  0.244292  0.603053  0.370968    0.0  0.00  0.333333
1    0.166667  0.339623  0.283105  0.885496  0.564516    0.0  0.00  0.666667
2    0.250000  0.339623  0.178082  0.770992  0.225806    1.0  0.00  0.666667
3    0.562500  0.245283  0.251142  0.816794  0.129032    1.0  0.00  0.666667
4    0.583333  0.245283  0.520548  0.702290  0.096774    1.0  0.00  0.666667
..        ...       ...       ...       ...       ...    ...   ...       ...
298  0.583333  0.433962  0.262557  0.396947  0.032258    0.5  0.00  1.000000
299  0.333333  0.150943  0.315068  0.465649  0.193548    0.5  0.00  1.000000
300  0.812500  0.471698  0.152968  0.534351  0.548387    0.5  0.50  1.000000
301  0.583333  0.339623  0.011416  0.335878  0.193548    0.5  0.25  1.000000
302  0.583333  0.339623  0.251142  0.786260  0.000000    0.5  0.25  0.666667

[303 rows x 8 columns]

In [17]:
Hasil = Hasil.drop(columns = dataNormalisasi)
Hasil = pd.concat([Hasil, hasilNormalisasi], axis=1)
Hasil

cp  fbs  restecg  exang  sex  target       age  trestbps      chol  \
0     3    1        0      0    1       1  0.708333  0.481132  0.244292   
1     2    0        1      0    1       1  0.166667  0.339623  0.283105   
2     1    0        0      0    0       1  0.250000  0.339623  0.178082   
3     1    0        1      0    1       1  0.562500  0.245283  0.251142   
4     0    0        1      1    0       1  0.583333  0.245283  0.520548   
..   ..  ...      ...    ...  ...     ...       ...       ...       ...   
298   0    0        1      1    0       0  0.583333  0.433962  0.262557   
299   3    0        1      0    1       0  0.333333  0.150943  0.315068   
300   0    1        1      0    1       0  0.812500  0.471698  0.152968   
301   0    0        1      1    1       0  0.583333  0.339623  0.011416   
302   1    0        0      0    0       0  0.583333  0.339623  0.251142   

      thalach   oldpeak  slope    ca      thal  
0    0.603053  0.370968    0.0  0.00  0.333333  
1    0.885496  0.564516    0.0  0.00  0.666667  
2    0.770992  0.225806    1.0  0.00  0.666667  
3    0.816794  0.129032    1.0  0.00  0.666667  
4    0.702290  0.096774    1.0  0.00  0.666667  
..        ...       ...    ...   ...       ...  
298  0.396947  0.032258    0.5  0.00  1.000000  
299  0.465649  0.193548    0.5  0.00  1.000000  
300  0.534351  0.548387    0.5  0.50  1.000000  
301  0.335878  0.193548    0.5  0.25  1.000000  
302  0.786260  0.000000    0.5  0.25  0.666667  

[303 rows x 14 columns]

In [18]:
percent_amount_of_test_data = 0.3

Menghitung Data
```
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test

In [19]:
matrices_X = Hasil.iloc[:,0:14].values
matrices_Y = Hasil.iloc[:,0].values

In [20]:
X1 = Hasil.iloc[:,0:14].values
Y1 = Hasil.iloc[:, 0].values

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X1, Y1, test_size = percent_amount_of_test_data, random_state=0)

In [22]:
X_train.shape

(212, 14)

In [23]:
Y1

array([3, 2, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 1, 3, 3, 2, 2, 3, 0, 3, 0, 2,
       0, 2, 3, 1, 2, 2, 2, 2, 1, 0, 1, 2, 3, 2, 2, 2, 2, 2, 2, 1, 0, 0,
       2, 1, 2, 2, 2, 0, 2, 0, 2, 2, 2, 1, 0, 0, 3, 0, 2, 1, 3, 1, 2, 0,
       2, 1, 1, 0, 2, 2, 1, 0, 2, 1, 2, 1, 1, 2, 2, 1, 2, 3, 0, 2, 2, 1,
       2, 0, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 3, 3, 1, 2, 2, 2, 3, 0, 1, 0,
       0, 2, 2, 0, 1, 2, 2, 3, 1, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 1, 2, 1,
       1, 1, 1, 0, 2, 1, 0, 0, 2, 0, 2, 0, 2, 1, 2, 3, 2, 2, 0, 0, 3, 2,
       2, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 2, 1, 1, 2, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 3, 0, 0, 0, 1, 0, 3, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0,
       3, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0,

In [24]:
### Dictionary to store model and its accuracy

model_accuracy = OrderedDict()

### Dictionary to store model and its precision

model_precision = OrderedDict()

### Dictionary to store model and its recall

model_recall = OrderedDict()

Naive Bayes

In [25]:
naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)
Y_pred_nb = naive_bayes_classifier.predict(X_test)

cm = confusion_matrix(y_test, Y_pred_nb)

print('Confusion matrix for Gaussian Naive Bayes\n',cm)

naive_bayes_accuracy = round(100 * accuracy_score(y_test, Y_pred_nb), 2)
model_accuracy['Gaussian Naive Bayes'] = naive_bayes_accuracy

naive_bayes_precision = round(100 * precision_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_precision['Gaussian Naive Bayes'] = naive_bayes_precision

naive_bayes_recall = round(100 * recall_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_recall['Gaussian Naive Bayes'] = naive_bayes_recall

print('The accuracy of this model is {} %.'.format(naive_bayes_accuracy))
print('The precision of this model is {} %.'.format(naive_bayes_precision))
print('The recall of this model is {} %.'.format(naive_bayes_recall))

Confusion matrix for Gaussian Naive Bayes
 [[41  0  0  0]
 [ 0 17  0  0]
 [ 0  0 28  0]
 [ 0  0  0  5]]
The accuracy of this model is 100.0 %.
The precision of this model is 100.0 %.
The recall of this model is 100.0 %.


In [26]:
Y_pred_nb

array([0, 3, 3, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 2, 0, 2, 0, 2, 0, 0,
       1, 0, 1, 2, 0, 0, 2, 1, 2, 0, 1, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2, 0,
       3, 1, 2, 2, 0, 1, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 0, 2, 2, 2, 0, 1,
       3, 0, 0, 0, 0, 2, 1, 0, 0, 2, 2, 0, 2, 3, 0, 0, 0, 2, 0, 1, 0, 2,
       2, 0, 0])

In [27]:
clf = GaussianNB()
clf.fit(matrices_X, matrices_Y)
clf_pf = GaussianNB()
clf_pf.partial_fit(matrices_X, matrices_Y, np.unique(matrices_Y))

GaussianNB()

In [28]:
FIRST_IDX = 0

In [29]:
result_test_naive_bayes = clf_pf.predict([[3,	1,	0,	0,	1,	1,	0.708333,	0.481132,	0.244292, 0.603053, 0.370968, 0, 0, 0.333333]])[FIRST_IDX]
print(f"Data Baru SEX :  {result_test_naive_bayes} Pada metode Gaussian Naive Bayes model")

Data Baru SEX :  3 Pada metode Gaussian Naive Bayes model


In [30]:
K = 3
knn = KNeighborsClassifier(n_neighbors = K)

knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [31]:
Y_pred_knn = knn.predict(X_test)

In [32]:
knn.score(X_test, y_test)

0.989010989010989

In [33]:
# Custom value to predict
result_test_knn = knn.predict([[3,	1,	0,	0,	1,	1,	0.708333,	0.481132,	0.244292, 0.603053, 0.370968, 0, 0, 0.333333]])
print(f"Data Baru Temasuk sex : {result_test_knn[FIRST_IDX]} Pada metode KNN model")

Data Baru Temasuk sex : 3 Pada metode KNN model


In [34]:
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import pickle
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)
# save the model to disk
filename = 'model_heart_KNN.pkl'
pickle.dump(model, open(filename, 'wb'))

KNN

In [35]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [36]:
#periksa jumlah baris dan kolom dalam dataset
data.shape

(303, 14)

In [37]:
#Pilih data menjadi variabel independen 'X' dan variabel 'Y'
X = data.iloc[:, 0:13].values 
Y = data.iloc[:,13].values
#ATAU
#X=df.drop("Klasifikasi", sumbu=1)
#Y=df["Klasifikasi"]

In [38]:
## Jika ada yang melihat data dengan fitur (X)
all_columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg','thalach', 'exang', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

X = pd.DataFrame(X,columns=all_columns[0:13])
all_columns[0:13]
X.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  exang  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0    0.0    2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0    0.0    3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0    0.0    1.4   
3  56.0  1.0  1.0     120.0  236.0  0.0      1.0    178.0    0.0    0.8   
4  57.0  0.0  0.0     120.0  354.0  0.0      1.0    163.0    1.0    0.6   

   oldpeak  slope   ca  
0      0.0    0.0  1.0  
1      0.0    0.0  2.0  
2      2.0    0.0  2.0  
3      2.0    0.0  2.0  
4      2.0    0.0  2.0

In [39]:
Y[:]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [40]:
#Pisahkan dataset menjadi 80% set Pelatihan dan 20% set Pengujian
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)

In [41]:

#Penskalaan Fitur
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train[:5]

array([[-1.32773282, -1.43641607,  0.98584243, -0.57412513, -0.63267424,
        -0.41803981,  0.90163913,  0.65626162, -0.70929937, -0.72460883,
        -0.66169316, -0.70710678, -0.46472917],
       [ 1.24903178, -1.43641607,  0.98584243,  0.83106608,  0.58543663,
        -0.41803981, -0.97936664,  0.09400698, -0.70929937, -0.89249331,
        -0.66169316,  0.26516504, -0.46472917],
       [ 0.35276583,  0.69617712,  0.98584243,  0.47976828, -0.67015457,
         2.39211668, -0.97936664,  0.65626162, -0.70929937, -0.89249331,
         0.95577901, -0.70710678, -0.46472917],
       [ 0.91293205, -1.43641607, -0.92274852, -0.45702586, -0.93251691,
        -0.41803981,  0.90163913, -0.59799874,  1.40984195, -0.89249331,
        -0.66169316, -0.70710678, -0.46472917],
       [ 0.24073259,  0.69617712,  0.03154696,  1.29946315, -0.27661106,
        -0.41803981, -0.97936664,  0.61301126, -0.70929937, -0.89249331,
         0.95577901,  0.26516504, -0.46472917]])

In [42]:
def models(X_train,Y_train):
  
  #Menggunakan Metode KNeighborsClassifier dari kelas tetangga untuk menggunakan algoritma Nearest Neighbor
  from sklearn.neighbors import KNeighborsClassifier
  knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
  knn.fit(X_train, Y_train)

    
  #mencetak akurasi model pada data pelatihan.
  print(knn.score(X_train, Y_train))
  return knn

model = models(X_train,Y_train)



0.8677685950413223
